### ISSUE TITLE
quest 2 avatar stats settings dont show up

### ISSUE THREAD

**Issue by MarksNewHat98** [FirEmerald/AvatarStatsLoader#2]
![image](https://github.com/FirEmerald/AvatarStatsLoader/assets/93878714/58aa680d-1734-4072-ac36-a870f8338e8a)

main UserData folder does not contain a AvatarStats folder either

**Comment by MarksNewHat98** [comment]
its most likely a lemon loader issue

![image](https://github.com/FirEmerald/AvatarStatsLoader/assets/93878714/774b6080-2a18-46f5-ad7a-fac5db7502f2)

what the buggy code outputs

![image](https://github.com/FirEmerald/AvatarStatsLoader/assets/93878714/0d635fee-75be-4ba3-bba6-8c6b470a8914)

what the melonloader code does
(BaseDirectory is GameDirectory which is string.Copy(internal method called GetGameDirectory))

**Comment by FirEmerald** [comment]
did you save any avatar stats?

**Comment by MarksNewHat98** [comment]
yes but all of the settings get stored in the root folder

**Comment by FirEmerald** [comment]
pushed a new update, version 1.2.2. try it out when it goes live. Might not do anything, all I did was swap from using string concatenation to Path.Combine which should at least fix using the wrong path separator.

**Comment by MarksNewHat98** [comment]
you forgot to update the file saving
and yes the folder now is located in userdata

**Comment by FirEmerald** [comment]
Fixed it, version 1.2.3 is now uploaded to thunderstore but will take an unknown amount of time to be visible
